services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/mongo/data:/data/db
  server:
    depends_on:
      - mongodb
    build: .
    image: 265632502439.dkr.ecr.us-east-1.amazonaws.com/andres-app-server
    command: npm start
    ports:
      - 5000:5000
    links:
      - mongodb